### ISSUE TITLE
Repository name

### ISSUE THREAD

**Issue by aginika** [procrob/procrob_functional#3]
This package is awesome !

Because repository name is not equal to project name, I have some errors when do catkin_make.
And it will be also a bit confusing.
Is it able to change from procrob_functional to face_recognition? Just a propsal, so if there are some reason for this repository name, please never mind.

**Comment by 130s** [comment]
This issue still holds (so should be re-opened). I had to change the folder name to `face_recognition` as @aginika suggested, in order to get the tutorial works.

> The current repository name is due to some historical reasons. I'll fix it at some time. It shouldn't make any problem though.

Here I'm not sure your plan @procrob. Were you going to change the repo name as suggested, or replace all face_recognition strings to `procrob_functional`?

**Comment by procrob** [comment]
Hi @130s , I changed the repository name to face_recognition. I hope this solves the issue.

Thanks for the info,
Pouyan

**Comment by 130s** [comment]
Yeah, LGTM. Thanks!
